/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sw_CDMA2000_TC_decoder.h)                                  */
/* BINDTOOL_HEADER_FILE_HASH(66e6b36c605073abf99eee851b11f617)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <zynq/sw_CDMA2000_TC_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <sw_CDMA2000_TC_decoder_pydoc.h>

void bind_sw_CDMA2000_TC_decoder(py::module& m)
{

    using sw_CDMA2000_TC_decoder = gr::zynq::sw_CDMA2000_TC_decoder;


    py::class_<sw_CDMA2000_TC_decoder, gr::block, gr::basic_block,
        std::shared_ptr<sw_CDMA2000_TC_decoder>>(m, "sw_CDMA2000_TC_decoder", D(sw_CDMA2000_TC_decoder))

        .def(py::init(&sw_CDMA2000_TC_decoder::make),
           py::arg("debug"),
           D(sw_CDMA2000_TC_decoder,make)
        )
        



        ;




}
