/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sw_CDMA2000_TC_encoder.h)                                  */
/* BINDTOOL_HEADER_FILE_HASH(b57484308aabd243a44d48b760049b6f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <zynq/sw_CDMA2000_TC_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <sw_CDMA2000_TC_encoder_pydoc.h>

void bind_sw_CDMA2000_TC_encoder(py::module& m)
{

    using sw_CDMA2000_TC_encoder = gr::zynq::sw_CDMA2000_TC_encoder;


    py::class_<sw_CDMA2000_TC_encoder, gr::block, gr::basic_block,
        std::shared_ptr<sw_CDMA2000_TC_encoder>>(m, "sw_CDMA2000_TC_encoder", D(sw_CDMA2000_TC_encoder))

        .def(py::init(&sw_CDMA2000_TC_encoder::make),
           py::arg("debug"),
           D(sw_CDMA2000_TC_encoder,make)
        )
        



        ;




}
