/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sw_complex_matrix_difference_ratio.h)                      */
/* BINDTOOL_HEADER_FILE_HASH(0fd5e4af2f6bb4a41f9685e46cc69e11)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <zynq/sw_complex_matrix_difference_ratio.h>
// pydoc.h is automatically generated in the build directory
#include <sw_complex_matrix_difference_ratio_pydoc.h>

void bind_sw_complex_matrix_difference_ratio(py::module& m)
{

    using sw_complex_matrix_difference_ratio = gr::zynq::sw_complex_matrix_difference_ratio;


    py::class_<sw_complex_matrix_difference_ratio, gr::block, gr::basic_block,
        std::shared_ptr<sw_complex_matrix_difference_ratio>>(m, "sw_complex_matrix_difference_ratio", 
                                                      D(sw_complex_matrix_difference_ratio))

        .def(py::init(&sw_complex_matrix_difference_ratio::make),
           py::arg("debug"),
           D(sw_complex_matrix_difference_ratio, make)
        )
        



        ;




}








