/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sw_vector_permute.h)                                       */
/* BINDTOOL_HEADER_FILE_HASH(814bb0abd1582d76c59663424ecca779)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <zynq/sw_vector_permute.h>
// pydoc.h is automatically generated in the build directory
#include <sw_vector_permute_pydoc.h>

void bind_sw_vector_permute(py::module& m)
{

    using sw_vector_permute = gr::zynq::sw_vector_permute;


    py::class_<sw_vector_permute, gr::block, gr::basic_block,
        std::shared_ptr<sw_vector_permute>>(m, "sw_vector_permute", 
                                                      D(sw_vector_permute))

        .def(py::init(&sw_vector_permute::make),
           py::arg("debug"),
           D(sw_vector_permute, make)
        )
        



        ;




}








