/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zynq_loopback_legacy.h)                                    */
/* BINDTOOL_HEADER_FILE_HASH(3ea96687593535349d738b0779be9512)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <zynq/zynq_loopback_legacy.h>
// pydoc.h is automatically generated in the build directory
#include <zynq_loopback_legacy_pydoc.h>

void bind_zynq_loopback_legacy(py::module& m)
{

    using zynq_loopback_legacy    = gr::zynq::zynq_loopback_legacy;


    py::class_<zynq_loopback_legacy, gr::block, gr::basic_block,
        std::shared_ptr<zynq_loopback_legacy>>(m, "zynq_loopback_legacy", D(zynq_loopback_legacy))

        .def(py::init(&zynq_loopback_legacy::make),
           py::arg("device_index"),
           py::arg("batch_size"),
           py::arg("load"),
           py::arg("debug"),
           D(zynq_loopback_legacy,make)
        )
        



        ;




}








