/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zynq_loopback.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ab3f6a80592ca3260006379aa39392c9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <zynq/zynq_loopback.h>
// pydoc.h is automatically generated in the build directory
#include <zynq_loopback_pydoc.h>

void bind_zynq_loopback(py::module& m)
{

    using zynq_loopback    = gr::zynq::zynq_loopback;


    py::class_<zynq_loopback, gr::block, gr::basic_block,
        std::shared_ptr<zynq_loopback>>(m, "zynq_loopback", D(zynq_loopback))

        .def(py::init(&zynq_loopback::make),
           py::arg("device_index"),
           py::arg("batch_size"),
           py::arg("load"),
           D(zynq_loopback,make)
        )
        



        ;




}








