/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zynq_complex_matrix_inv_10x10.h)                           */
/* BINDTOOL_HEADER_FILE_HASH(3a88e8288e7a34697cec1ce8e69a4c9c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <zynq/zynq_complex_matrix_inv_10x10.h>
// pydoc.h is automatically generated in the build directory
#include <zynq_complex_matrix_inv_10x10_pydoc.h>

void bind_zynq_complex_matrix_inv_10x10(py::module& m)
{

    using zynq_complex_matrix_inv_10x10 = gr::zynq::zynq_complex_matrix_inv_10x10;


    py::class_<zynq_complex_matrix_inv_10x10, gr::block, gr::basic_block,
        std::shared_ptr<zynq_complex_matrix_inv_10x10>>(m, "zynq_complex_matrix_inv_10x10", D(zynq_complex_matrix_inv_10x10))

        .def(py::init(&zynq_complex_matrix_inv_10x10::make),
           py::arg("device_index"),
           py::arg("debug"),
           D(zynq_complex_matrix_inv_10x10,make)
        )
        



        ;




}
