/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zynq_fft.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6132cb728fc940a1d0112f33f24d5e02)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <zynq/zynq_fft.h>
// pydoc.h is automatically generated in the build directory
#include <zynq_fft_pydoc.h>

void bind_zynq_fft(py::module& m)
{

    using zynq_fft    = gr::zynq::zynq_fft;


    py::class_<zynq_fft, gr::block, gr::basic_block,
        std::shared_ptr<zynq_fft>>(m, "zynq_fft", D(zynq_fft))

        .def(py::init(&zynq_fft::make),
           py::arg("device_index"),
           py::arg("debug"),
           D(zynq_fft,make)
        )
        



        ;




}








